# Create the environment:
# mamba env create -f environment-common.yml 
# or if you really want to use conda
# conda env create -f environment-common.yml
name: stece

channels:
  - conda-forge

dependencies:
  - python=>3.9,<3.10
  - cdo=2.4.0
  - eccodes>=2.31.0,<2.34.0 
  - ipykernel
  - numpy
  - scipy
  - xarray=2023
  - dask
  - pandas=1.5.3
  - matplotlib
  - netcdf4
  - python-cdo
  - ruamel.yaml
  - nc-time-axis
  - gsw
  - psutil
  - pip
  - pip:
    - -e .
