- base.context:
    job:
      amipfr:
        exe: "{{experiment.src_dir}}/amip-forcing/bin/amip-forcing.exe"
    experiment:
      amipfr:
        forcing:
          dir: "{{experiment.ini_dir}}/amip-forcing"
          sst: tosbcs_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-3_gn_187001-201706.nc
          sic: siconcbcs_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-3_gn_187001-201706.nc
