# Atm-oce coupling frequency lookup table
- base.context:
    model_config:
      oasis:
        cpl_dt:
          TCO95-eORCA1:  2700  # coupling every time step
          TL159-eORCA1: 10800  # 3hr coupling

- when: '"oifs" in model_config.components and "nemo" in model_config.components'
  do:
    - base.context:
        model_config:
          oasis:
            oifs_nemo:
              dt: "{{ model_config.oasis.cpl_dt[model_config.oifs.grid.name + '-' + model_config.nemo.grid.name] }}"
            nemo_oifs:
              dt: !noparse "{{ model_config.oasis.oifs_nemo.dt }}"
    - when: not model_config.oasis.oifs_nemo.dt
      base.exit:
        msg: "ERROR: Missing coupling frequency for {{ model_config.oifs.grid.name + '-' + model_config.nemo.grid.name }}"

- when: '"amipfr" in model_config.components and "oifs" in model_config.components'
  base.context:
    model_config:
      oasis:
        amipfr_oifs:
          dt: "{{ 24*3600 }}"
