- base.context:
    experiment:
      run_dir: !noparse "/ec/res4/scratch/itas/ece4/{{experiment.id}}"
      base_dir: !noparse "/ec/res4/hpcperm/itas/src/gitlab/ecearth4/"
      src_dir: !noparse "{{experiment.base_dir}}/sources"
      ini_dir: !noparse "/ec/res4/hpcperm/itas/data/v4-trunk"

      monitoring:
        # To activate monitoring, set
        #   experiment.monitoring.activated: true
        # in the experiment configuration.
        # In order to upload the monitoring results to Redmine, replace
        # REDMINE_API_KEY below with your real Redmine API key from
        # https://dev.ec-earth.org/my/account
        redmine_api_key: REDMINE_API_KEY

        # If redmine_api_key is not a valid key (unset or REDMINE_API_KEY), then
        # a Markdown representation of monitoring results is created locally in
        # the monitoring/markdown directory.
